# Generated by Django 4.2.7 on 2023-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod_bezIndeksa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_azuriranja', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod_SIndeksom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_azuriranja', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena', 'datum_kreiranja'], name='main_proizv_naziv_2a57a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_KriviIndeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_azuriranja', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['datum_kreiranja', 'naziv', 'cijena'], name='main_proizv_datum_k_02c197_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_DioIndeksa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_azuriranja', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena'], name='main_proizv_naziv_cad226_idx')],
            },
        ),
    ]
