# Generated by Django 4.2.7 on 2023-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod_bezindeksa',
            name='datum_azuriranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_bezindeksa',
            name='datum_kreiranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_dioindeksa',
            name='datum_azuriranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_dioindeksa',
            name='datum_kreiranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_kriviindeks',
            name='datum_azuriranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_kriviindeks',
            name='datum_kreiranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_sindeksom',
            name='datum_azuriranja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proizvod_sindeksom',
            name='datum_kreiranja',
            field=models.DateField(),
        ),
    ]
