# Generated by Django 4.2.7 on 2023-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_proizvod_bezindeksa_cijena_random_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod_bezIndeksa_MaloRedaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='proizvod_bezindeksa',
            name='cijena_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_bezindeksa',
            name='naziv_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_dioindeksa',
            name='cijena_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_dioindeksa',
            name='naziv_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_kriviindeks',
            name='cijena_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_kriviindeks',
            name='naziv_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_sindeksom',
            name='cijena_random',
        ),
        migrations.RemoveField(
            model_name='proizvod_sindeksom',
            name='naziv_random',
        ),
        migrations.CreateModel(
            name='Proizvod_SIndeksom_VelikaKard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena', 'datum_kreiranja'], name='main_proizv_naziv_e26fbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_SIndeksom_MaloRedaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena', 'datum_kreiranja'], name='main_proizv_naziv_42942d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_KriviIndeks_VelikaKard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['datum_kreiranja', 'naziv', 'cijena'], name='main_proizv_datum_k_256297_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_DioIndeksa_VelikaKard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena'], name='main_proizv_naziv_15ca71_idx')],
            },
        ),
    ]
