# Generated by Django 4.2.7 on 2023-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_proizvod_bezindeksa_maloredaka_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proizvod_kriviindeks',
            name='main_proizv_datum_k_02c197_idx',
        ),
        migrations.RemoveIndex(
            model_name='proizvod_kriviindeks_velikakard',
            name='main_proizv_datum_k_256297_idx',
        ),
        migrations.AddIndex(
            model_name='proizvod_kriviindeks',
            index=models.Index(fields=['datum_kreiranja', 'cijena', 'naziv'], name='main_proizv_datum_k_337eae_idx'),
        ),
        migrations.AddIndex(
            model_name='proizvod_kriviindeks_velikakard',
            index=models.Index(fields=['datum_kreiranja', 'cijena', 'naziv'], name='main_proizv_datum_k_2664e2_idx'),
        ),
    ]
