# Generated by Django 4.2.7 on 2023-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_proizvod_kriviindeks_main_proizv_datum_k_02c197_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod_SIndeksom_VelikaKard_Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena', 'datum_kreiranja'], name='main_proizv_naziv_26f936_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_SIndeksom_Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupna_kolicina', models.PositiveIntegerField(default=0)),
                ('datum_kreiranja', models.DateField()),
                ('datum_azuriranja', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['naziv', 'cijena', 'datum_kreiranja'], name='main_proizv_naziv_7d9c7a_idx')],
            },
        ),
    ]
